### ISSUE TITLE
New resistor configuration in errata.txt

### ISSUE THREAD

**Issue by djorr5** [kiu/lofence#16]
Hi, I saw this had activity starting up not that long ago and thought I might join the party ;).

In the errata.txt. OP makes mention of changing the resistor configuration from:
 [Fence+]--[10M]--[10M]--[1M]--[Measure]--[5k8]--[Fence-/GND]

to:
 [+12kV]--[10M]--[1M]--[Measure]--[5k8]--[GND]--[10M]--[Fence-]

Assuming so that the Fence- is possible earth (as in poke in an earth spike) and GND is ground referance on the PCB. However when I put the updated resistor values into falstad.com and with a 12kV input I was reading 6.28V at the opamp input. Isn't this too high for the opamp? 

Or am I completely missing something?

Sorry for making it an issue but I saw some other do it and thought this would be the best way. 

Great project by the way!!

**Comment by jpmeijers** [comment]
Did you remember to move the curcuit's GND connection to between the 5k8 and 10M resistor?

"GND" is just some arbitrary chosen reference. The errata changes this reference to be isolated from the fence's negative line (for two line systems). This is good, because both the "positive" and "negative" lines will shock you if you touch them, and connecting one of these lines to GND will put the circuit and antenna at that same level - ie. the antenna will shock you just like the fence.

Maybe share a screenshot of your two simulations so we can see if there isn't a mistake in there. Circuit theory says the two voltage divider circuits should result in the same voltage between GND and Measure.

**Comment by djorr5** [comment]
I did move the GND connection. But what I may not have done correctly is earthed the return wire of the fence. Here (australia) majority of fences have an earth spike and run just the one hot wire. So I was just wondering if that would affect the new layout of your voltage divider. Please see screenshot of a simulation I ran. Might not have it configured correctly, but I simulated the max voltage as a DC to see the highest level. It is set at 12kV. 

![image](https://github.com/kiu/lofence/assets/5736813/acf745b7-ef38-4f2f-ace9-115f86629ef6)

**Comment by kiu** [comment]
https://falstad.com/circuit/circuitjs.html?ctz=CQAgjCAMB0l3BWcMBMcUHYMGZIA4UA2ATmIxAUgpABZsKBTAWjDACgAnEFFG8DQtzx5+gqmHjxOIXHzACZhEfLEU8caWBpyFaZQvGSpXbHh2Dt+1RKOQ2Ad269R3fC7uPZLlMPcOZZi7YSn4AbuDaIOq0NCLR4hTiaHBQqTAI-lp80Vl+jpZRVAUqUGwADjKQfLxUwSI1Mmn+dUEhDR6V1TS1VX4A9sgghHxFkMQiSDAQ4mxAA

![image](https://github.com/kiu/lofence/assets/785968/2f1590cb-6557-49be-90a9-b54b621e607a)

**Comment by djorr5** [comment]
Ah ok. Understood.

**Comment by djorr5** [comment]
Ah ok. Understood.
